// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stella.FeatureManagement.Dashboard.Data;

#nullable disable

namespace Stella.FeatureManagement.Dashboard.Data.Migrations
{
    [DbContext(typeof(FeatureFlagDbContext))]
    [Migration("20261006092548_AddFeatureFlagUsage")]
    partial class AddFeatureFlagUsage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("features")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("integer");

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Parameters")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId");

                    b.ToTable("FeatureFilters", "features");
                });

            modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Application")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasDefaultValue("Default");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FeatureFlags", "features");
                });

            modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFlagUsage", b =>
                {
                    b.Property<int>("FeatureFlagId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("DisabledCount")
                        .HasColumnType("bigint");

                    b.Property<long>("EnabledCount")
                        .HasColumnType("bigint");

                    b.HasKey("FeatureFlagId", "Date");

                    b.ToTable("FeatureFlagUsages", "features");
                });

            modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFilter", b =>
                {
                    b.HasOne("Stella.FeatureManagement.Dashboard.Data.FeatureFlag", "FeatureFlag")
                        .WithMany("Filters")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFlagUsage", b =>
                {
                    b.HasOne("Stella.FeatureManagement.Dashboard.Data.FeatureFlag", "FeatureFlag")
                        .WithMany("Usages")
                        .HasForeignKey("FeatureFlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureFlag");
                });

            modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFlag", b =>
                {
                    b.Navigation("Filters");

                    b.Navigation("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
