// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stella.FeatureManagement.Dashboard.Data;

#nullable disable

namespace Stella.FeatureManagement.Dashboard.Data.Migrations;

[DbContext(typeof(FeatureFlagDbContext))]
partial class FeatureFlagDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

        modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFilter", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<int>("FeatureFlagId")
                .HasColumnType("INTEGER");

            b.Property<string>("FilterType")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<string>("Parameters")
                .HasMaxLength(4000)
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("FeatureFlagId");

            b.ToTable("FeatureFilters", (string)null);
        });

        modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFlag", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("TEXT");

            b.Property<bool>("IsEnabled")
                .HasColumnType("INTEGER");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("Name")
                .IsUnique();

            b.ToTable("FeatureFlags", (string)null);
        });

        modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFilter", b =>
        {
            b.HasOne("Stella.FeatureManagement.Dashboard.Data.FeatureFlag", "FeatureFlag")
                .WithMany("Filters")
                .HasForeignKey("FeatureFlagId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("FeatureFlag");
        });

        modelBuilder.Entity("Stella.FeatureManagement.Dashboard.Data.FeatureFlag", b =>
        {
            b.Navigation("Filters");
        });
#pragma warning restore 612, 618
    }
}
